{"name": "Негативный тест авторизации существующего пользователя", "status": "passed", "description": "Негативный тест. Получение  в тело ответа. code == 403 и наличия в ответе кода \"message\": \"User already exists\"", "start": 1726480454406, "stop": 1726480455418, "uuid": "0f6f5c7d-3e2a-43bb-b039-45ed3ad833b5", "historyId": "4654aa6cdd3b277f54df0d45fd4cb639", "testCaseId": "4654aa6cdd3b277f54df0d45fd4cb639", "fullName": "tests.test_registration.TestRegistration#test_repeat_registration_of_the_existing_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_registration"}, {"name": "subSuite", "value": "TestRegistration"}, {"name": "host", "value": "LAPTOP-KL5MP4V8"}, {"name": "thread", "value": "4264-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_registration"}]}